# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : Nexus Site 1
author :
  name : Saurabh Mishra
  email : saurabhmishra.iitg@gmail.com
  github : saurabhmishraiitg

#theme: minima
#show_excerpts: true
#header_pages:
#  - about.md
#  - portfolio.md
#minima:
#  skin: solarized

theme: jekyll-theme-minimal
logo: logo2.jpg